# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37475596d400358a55d91449152aacfb47eca42d6bc05887e5c90f1ea85c50ac88019e1638a87704d1d49b74b3b2e29f4cdabd9fed13d86e6db09c1ca100b30d

test:
  secret_key_base: 20cd4b94e5c40a1542ca73eed59548971243a7bcc631fc0a0cfb7ea2ab9dbfd7d3702c9c88f28806b7a8ba84e45e6d46252f1cb04df06a7d55f65db8b33c2cee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
